public enum TokenType {
    // Single character

    BANGBANG, OPEN_CURLY, CLOSED_CURLY, VERTICAL_PIPE, OPEN_SQUARE, CLOSED_SQUARE, OPEN_PAREN, CLOSED_PAREN,
    PLUS, MINUS, TIMES, DIVIDE,
    CARET, PERCENT,
    QUESTION, APPROX, GREATER, LESS, GEQ, LEQ,
    PERIOD,
    BACKSLASH,

    // Double character

    ASSIGNMENT,
    NOT_QUESTION, NOT_APPROX,
    DOUBLE_QUESTION, GEQ_QUESTION, LEQ_QUESTION,
    DOUBLE_DIVIDE,
    INCREMENT, DECREMENT,
    BACKSLASH_PERIOD, PERIOD_BACKSLASH,

    // Triple plus characters

    NOT_DOUBLE_QUESTION,
    PLUS_ASSIGNMENT, MINUS_ASSIGNMENT, TIMES_ASSIGNMENT, DIVIDE_ASSIGNMENT,
    CARET_ASSIGNMENT, PERCENT_ASSIGNMENT,

    // Literals

    IDENTIFIER, NUMBER, STRING,

    // Keywords

    NUM_KEYWORD, STR_KEYWORD, TF_KEYWORD, VAR_KEYWORD, FUNC_KEYWORD, ARR_KEYWORD,
    FOR_KEYWORD, WHEN_KEYWORD, LOOP_KEYWORD,
    OF_KEYWORD, COUNT_KEYWORD,
    NOTHING_KEYWORD,
    AND_KEYWORD, OR_KEYWORD, NOT_KEYWORD,
    NAND_KEYWORD, NOR_KEYWORD, XOR_KEYWORD, XNOR_KEYWORD, IMPLIES_KEYWORD,
    IF_KEYWORD,
    BUTIF_KEYWORD,
    BUT_KEYWORD,
    TRUE_KEYWORD, FALS_KEYWORD
}